-------------------------------------------------------------------------------
Test set: qa.gov.customs.authentication.UserMasterJpaTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 35.14 s <<< FAILURE! - in qa.gov.customs.authentication.UserMasterJpaTest
jpaTestForUserGetting(qa.gov.customs.authentication.UserMasterJpaTest)  Time elapsed: 1.185 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at qa.gov.customs.authentication.UserMasterJpaTest.jpaTestForUserGetting(UserMasterJpaTest.java:41)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at qa.gov.customs.authentication.UserMasterJpaTest.jpaTestForUserGetting(UserMasterJpaTest.java:41)
Caused by: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at qa.gov.customs.authentication.UserMasterJpaTest.jpaTestForUserGetting(UserMasterJpaTest.java:41)
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at qa.gov.customs.authentication.UserMasterJpaTest.jpaTestForUserGetting(UserMasterJpaTest.java:41)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at qa.gov.customs.authentication.UserMasterJpaTest.jpaTestForUserGetting(UserMasterJpaTest.java:41)

